version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:nightly
    container_name: gitlab
    restart: always
    hostname: 'capital-gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://10.10.9.29:1443'
        letsencrypt['enable'] = false
        prometheus_monitoring['enable'] = false
        gitlab_rails['gitlab_ssh_host'] = '10.10.9.29'
        gitlab_rails['gitlab_shell_ssh_port'] = 1022
        nginx['redirect_http_to_https'] = true
        nginx['listen_port']=443        
    ports:
      - '1080:80'
      - '1443:443'
      - '1022:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'

  gerrit:
    image: gerritcodereview/gerrit
    ports:
      - "29418:29418"
      - "3080:8080"
    depends_on:
      - ldap
    volumes:
      - /srv/gerrit/etc:/var/gerrit/etc
      - /srv/gerrit/git:/var/gerrit/git
      - /srv/gerrit/db:/var/gerrit/db
      - /srv/gerrit/index:/var/gerrit/index
      - /srv/gerrit/cache:/var/gerrit/cache
    environment:
      - CANONICAL_WEB_URL=http://10.10.9.29
    # command: init
