version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:nightly
    container_name: gitlab
    restart: always
    hostname: 'capital-gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'https://10.10.9.29:1443'
        letsencrypt['enable'] = false
        prometheus_monitoring['enable'] = false
        gitlab_rails['gitlab_ssh_host'] = '10.10.9.29'
        gitlab_rails['gitlab_shell_ssh_port'] = 1022
        nginx['redirect_http_to_https'] = true
        nginx['listen_port']=443        
        gitlab_rails['ldap_enabled'] = true
        ###! **remember to close this block with 'EOS' below**
        gitlab_rails['ldap_servers'] = YAML.load <<-'EOS'
          main: # 'main' is the GitLab 'provider ID' of this LDAP server
            label: 'LDAP'
            host: '10.10.9.29'
            port: 389
            uid: 'mail'
            bind_dn: 'cn=admin,dc=capital,dc=com'
            password: 'zhu88jie'
            encryption: 'plain' # "start_tls" or "simple_tls" or "plain"
            verify_certificates: false
            active_directory: false
            allow_username_or_email_login: false
            block_auto_created_users: false
            base: 'ou=people,dc=capital,dc=com'
            user_filter: ''
        EOS
    ports:
      - '1080:80'
      - '1443:443'
      - '1022:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'

  # gerrit:
  #   image: 'openfrontier/gerrit:3.3.2'
  #   restart: always
  #   hostname: 'gerrit-server'
  #   environment:
  #     - WEBURL=http://10.10.9.29:3080
  #     - DATABASE_TYPE=postgresql
  #     - DATABASE_HOSTNAME=10.10.9.29
  #     - DATABASE_PORT=5432
  #     - DATABASE_DATABASE=reviewdb
  #     - DATABASE_USERNAME=gerrit2
  #     - DATABASE_PASSWORD=zhu88jie
  #     - AUTH_TYPE=LDAP
  #     - LDAP_SERVER=ldap://10.10.9.29
  #     - LDAP_USERNAME=cn=admin,dc=capital,dc=com
  #     - LDAP_PASSWORD=zhu88jie
  #     - LDAP_ACCOUNTPATTERN=(&(mail=$${username}))
  #     - LDAP_ACCOUNTBASE=ou=people,dc=capital,dc=com
  #     - LDAP_ACCOUNTSSHUSERNAME=$${uid.toLowerCase}
  #     - LDAP_ACCOUNTFULLNAME=$${sn.toLowerCase}
  #     - GERRIT_INIT_ARGS=--install-plugin=replication --install-plugin=commit-message-length-validator --install-plugin=download-commands
  #   ports:
  #     - '3080:8080'
  #     - '29418:29418'
  #   volumes:
  #     - /srv/gerrit/etc:/var/gerrit/etc
  #     - /srv/gerrit/git:/var/gerrit/git
  #     - /srv/gerrit/db:/var/gerrit/db
  #     - /srv/gerrit/index:/var/gerrit/index
  #     - /srv/gerrit/cache:/var/gerrit/cache
  #   depends_on:
  #     - db

  # db:
  #   image: postgres:14.1-alpine
  #   container_name: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=zhu88jie
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - /srv/postgres/data:/var/lib/postgresql/data