version: '3'
services:
  openldap:
    image: osixia/openldap
    container_name: openldap
    environment:
      LDAP_TLS: 'false'
      # LDAP_TLS_CRT_FILENAME: 'fullchain.pem'
      # LDAP_TLS_KEY_FILENAME: 'privkey.pem'
      # LDAP_TLS_CA_CRT_FILENAME: 'fullchain.pem'
      LDAP_ORGANISATION: "capital"
      LDAP_DOMAIN: "capital.com"
      LDAP_BASE_DN: "dc=capital,dc=com"
      LDAP_ADMIN_PASSWORD: "zhu88jie"
      LDAP_TLS_CIPHER_SUITE: "NORMAL"
      LDAP_TLS_VERIFY_CLIENT: "allow"
    tty: true
    stdin_open: true
    volumes:
      - /srv/ldap/var_lib/:/var/lib/ldap
      - /srv/ldap/etc_slapd.d/:/etc/ldap/slapd.d
    ports:
      - "389:389"
      - "639:639"
    hostname: "ldap.capital.com"
  phpldapadmin:
    image: osixia/phpldapadmin
    container_name: phpldapadmin
    volumes:
       - /srv/ldap/certs:/container/service/phpldapadmin/assets/apache2/certs
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS_CRT_FILENAME: "ldap.crt"
      PHPLDAPADMIN_HTTPS_KEY_FILENAME: "ldap.key"
      PHPLDAPADMIN_HTTPS_CA_CRT_FILENAME: "ca.crt"
      #PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "0.0.0.0:8443:443"
    depends_on:
      - openldap
